CREATE TABLE IF NOT EXISTS user_list(
    id BIGINT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT(11) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
)